### ISSUE TITLE
About synthetic and real-world dataset

### ISSUE THREAD

**Issue by xingjinderhuoche** [ltwu6/malspc#1]
Thanks for the good work. I have two questions:
1、In synthetic data---ShapeNet, Is the deepmap D0 come from the renderer of cmplete project, and the input partial Pin is come from back-project?
2、In real-world data, Is the deepmap D0 and input partial point clould Pin get in the same way as synthetic data?

**Comment by ltwu6** [comment]
Thanks for your interest. 
1. D0 is rendered from the complete object,  and Pin is back-projected from D0.
2. The real-world data do not include depth maps since we only use them for testing.

**Comment by xingjinderhuoche** [comment]
Thanks a lot！
