### ISSUE TITLE
Request for Configuration and Pre-trained Weights of Improved P2C Model in Table1

### ISSUE THREAD

**Issue by XDUchpn** [ltwu6/malspc#3]
![image](https://github.com/user-attachments/assets/eba51521-c48b-46bb-a3c5-b7f4756876bd)
Hello,

I am currently working on self-supervised point cloud representation. I came across your impressive results in [Self-supervised 3D Point Cloud Completion via Multi-view Adversarial Learning] where your reproduced P2C model achieved significantly better performance compared to the original P2C paper.

To further analyze and understand the factors that contributed to this improvement, I would like to kindly request access to the configuration file and pre-trained weights used for your reproduced P2C model in this study. 

Thank you very much for considering my request. I look forward to your response and any insights you can share about your approach.

Best regards

**Comment by ltwu6** [comment]
Thanks for reaching out. The reason our reported results differ from those in P2C paper is that we used our own synthetic dataset rather than the one used by P2C.
